services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/testdb -schemas=public -user=dbuser -password=test -connectRetries=60 migrate
    volumes:
      - ./database/scripts:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb

  webapp:
    build: .
    environment:
      - AWS_CLIENT_ID=4mi8l3p7pcglt1ig1717qqjbtd
      - AWS_CLIENT_SECRET=opofijbm9p7t3ejdt417hr4uqabgdkgbig0idkr506f51ammkti
      - AWS_USER_POOL_ID=eu-west-1_5IuLp25AP
      - COGNITO_DOMAIN=https://greatnotes-security-levelup.auth.eu-west-1.amazoncognito.com
      - DB_NAME=testdb
      - DB_USER=dbuser
      - DB_HOST=db
      - DB_PASSWORD=test
      - DB_PORT=5432
      - API_PORT=3000
      - WEB_PORT=3000
      - ENV=development
    ports:
      - 3000:3000
    depends_on:
      - flyway