services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/testdb -schemas=public -user=dbuser -password=test -connectRetries=60 migrate
    volumes:
      - ./database/scripts:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb

  webapp:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - flyway