name: deploy-to-eb

on:
  push:
    branches: [ main ]
    paths-ignore: 
    - '.terraform/**'
    - 'database'
    - 'Dockerfile'
    - 'docker-compose.yml'
    - '.dockerignore'
    - '*.md'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Assume the deploy pipeline user role
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Get secrets by name and by ARN
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            credentials
          parse-json-secrets: true

      - name: Create .env file
        run: |
          cat > ./server/.env <<EOF
          DB_USER=${{ env.CREDENTIALS_USERNAME }}
          DB_HOST=${{ env.CREDENTIALS_HOST }}
          DB_NAME=${{ env.CREDENTIALS_DB_NAME }}
          DB_PORT=${{ env.CREDENTIALS_PORT }}
          DB_PASSWORD=${{ env.CREDENTIALS_PASSWORD }}
          AWS_CLIENT_ID=${{ secrets.AWS_CLIENT_ID}}
          AWS_CLIENT_SECRET=${{ secrets.AWS_CLIENT_SECRET }}
          AWS_USER_POOL_ID=${{ secrets.AWS_USER_POOL_ID }}
          ENV=production
          PORT=8081
          DOMAIN=https://great-notes.projects.bbdgrad.com
          EOF
      
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Building app
        run: |
          cd client && npm install && npm run build
          cd ../server && npm install
          cp -r ../.ebextensions .
          cp -r ../.platform .

      - name: Create ZIP deployment package
        run: cd server && zip -r ../bundle.zip .

      - name: Upload package to S3 bucket
        run: aws s3 cp bundle.zip s3://great-notes-state-bucket/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name great-notes-app \
          --source-bundle S3Bucket="great-notes-state-bucket",S3Key="bundle.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk update-environment --environment-name great-notes-app-env --version-label "ver-${{ github.sha }}"  
