name: Database Migration with Flyway

on:
  push:
    branches: 
      - sphe/feat/rds-connection-fix
    paths:
      - 'database/scripts/**'
      - 'database/flyway/**'

permissions:
  contents: read
  id-token: write

jobs:
  migrate-database:
    name: Run Flyway Migration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Assume the deploy pipeline user role
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get private key secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            private_key
            credentials
          parse-json-secrets: true

      - name: Store ssh key in pem file
        run: echo ${{ env.PRIVATE_KEY_PRIVATE_KEY_RFC1421 }} > ssh_key.pem
      
      - name: Configure ssh tunnel through bastion host
        run: |
          ssh -fN -v -L 5432:${{ env.CREDENTIALS_HOST }} ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} -i ssh_key.pem &
          PID=$!
          echo "SSH_PID=$(echo $PID)" >> $GITHUB_ENV

      - name: Generate flyway config file
        run: |
          cat > flyway.generated.conf <<EOF
          flyway.url=jdbc:postgresql://localhost:5432/${{ env.CREDENTIALS_DB_NAME }}
          flyway.user=${{ env.CREDENTIALS_USERNAME }}
          flyway.password=${{ env.CREDENTIALS_PASSWORD }}
          EOF
          cat database/flyway/flyway.conf >> flyway.generated.conf

      - name: Run Flyway Migration
        run: |
          sudo snap install flyway
          flyway migrate -configFiles=flyway.generated.conf
      
      - name: Terminate SSH tunnel
        run: kill -9 $SSH_PID
